---
abstract: 'perl5 vm golf'
author: ~
build_requires:
  Test::More: 0
  YAML: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Acme-PerlVMGolf
no_index:
  directory:
    - inc
    - t
requires:
  XSLoader: 0
  perl: 5.8.0
version: 0.01
